# Generated by Django 4.2.26 on 2025-12-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
