# Generated by Django 4.2.26 on 2025-12-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank')], default='mpesa', max_length=20),
        ),
    ]
