# Generated by Django 4.2.26 on 2025-12-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_mpesa_number_transaction_mpesa_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='mpesa_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mpesa_receipt',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payout_method',
        ),
    ]
