# Generated by Django 4.2.26 on 2025-12-05 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transaction_mpesa_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\- ]+$', 'Use digits and + - only')])),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('other', 'Other Official ID')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('platforms_supported', models.CharField(help_text='List exchanges / wallets you can service', max_length=255)),
                ('fiat_payout_methods', models.CharField(help_text='e.g. M-Pesa, Airtel Money, Bank wires', max_length=255)),
                ('crypto_addresses', models.TextField(help_text='List of addresses for supported assets')),
                ('daily_liquidity_capacity', models.DecimalField(decimal_places=2, help_text='USD equivalent you can process per day', max_digits=12)),
                ('compliance_experience', models.TextField(help_text='Describe AML/KYC controls you have previously followed')),
                ('has_aml_policy', models.BooleanField(default=False)),
                ('accepts_background_check', models.BooleanField(default=False)),
                ('terms_acknowledged', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
