# Generated by Django 4.2.26 on 2025-12-05 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_agentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agent_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
