# Generated by Django 4.2.26 on 2025-12-05 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_agentapplication_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='created_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
