# Generated by Django 4.2.26 on 2025-12-11 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_pricingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uploaded', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('completion_score', models.IntegerField(default=0)),
                ('limits_unlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
