# Generated by Django 4.2.26 on 2025-12-09 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pricingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
