# Generated by Django 4.2.26 on 2025-12-10 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_agentprofile_created_at_agentprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uploaded', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('completion_score', models.IntegerField(default=0)),
                ('limits_unlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
