# Generated by Django 4.2.26 on 2025-12-10 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_accountverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverification',
            name='completion_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountverification',
            name='id_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountverification',
            name='limits_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
