# Generated by Django 4.2.26 on 2025-12-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_accountverification_completion_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverification',
            name='id_document',
            field=models.FileField(upload_to='verification_docs/', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountverification',
            name='limits_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountverification',
            name='completion_score',
            field=models.IntegerField(default=0),
        ),
    ]
